apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-7336"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "diaggarw-7336"
  template:
    metadata:
      labels:
        app: "diaggarw-7336"
    spec:
      containers:
        - name: "diaggarw-7336"
          image: "aaaatiwarishubregistry.azurecr.io/diaggarw"
          ports:
          - containerPort: 8080