apiVersion : apps/v1
kind: Deployment
metadata:
  name: "allhandsaks-8a4d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "allhandsaks-8a4d"
  template:
    metadata:
      labels:
        app: "allhandsaks-8a4d"
    spec:
      containers:
        - name: "allhandsaks-8a4d"
          image: "aaaatiwarishubregistry.azurecr.io/allhandsaks"
          ports:
          - containerPort: 8080