apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishubaks2-f1f3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishubaks2-f1f3"
  template:
    metadata:
      labels:
        app: "aatiwarishubaks2-f1f3"
    spec:
      containers:
        - name: "aatiwarishubaks2-f1f3"
          image: "diaggarwtest.azurecr.io/aatiwarishubaks2f1f3"
          ports:
          - containerPort: 8080