apiVersion: v1
kind: Service
metadata:
    name: "aatiwarishubaks2-f1f3"
    labels:
        app: "aatiwarishubaks2-f1f3"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "aatiwarishubaks2-f1f3"