on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwtest.azurecr.io
        username: ${{ secrets.acr_diaggarwtest_username }}
        password: ${{ secrets.acr_diaggarwtest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t diaggarwtest.azurecr.io/aatiwarishubaks634b:${{ github.sha }}
        docker push diaggarwtest.azurecr.io/aatiwarishubaks634b:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aatiwarishubaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aatiwarishubaks634b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aatiwarishubaks634b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aatiwarishubaks634b
        container-registry-url: diaggarwtest.azurecr.io
        container-registry-username: ${{ secrets.acr_diaggarwtest_username }}
        container-registry-password: ${{ secrets.acr_diaggarwtest_password }}
        secret-name: aatiwarishubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aatiwarishubaks634b
        manifests: |
          ./manifests/deployment-634b.yml
          ./manifests/service-634b.yml
        images: |
          diaggarwtest.azurecr.io/aatiwarishubaks634b:${{ github.sha }}
        imagepullsecrets: |
          aatiwarishubdockerauth