on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwtest.azurecr.io
        username: ${{ secrets.acr_diaggarwtest_username }}
        password: ${{ secrets.acr_diaggarwtest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t diaggarwtest.azurecr.io/aatiwarishubaks2f1f3:${{ github.sha }}
        docker push diaggarwtest.azurecr.io/aatiwarishubaks2f1f3:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aatiwarishubaks2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aatiwarishubaks2f1f3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aatiwarishubaks2f1f3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aatiwarishubaks2f1f3
        container-registry-url: diaggarwtest.azurecr.io
        container-registry-username: ${{ secrets.acr_diaggarwtest_username }}
        container-registry-password: ${{ secrets.acr_diaggarwtest_password }}
        secret-name: aatiwarishubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aatiwarishubaks2f1f3
        manifests: |
          ./manifests/deployment-f1f3.yml
          ./manifests/service-f1f3.yml
        images: |
          diaggarwtest.azurecr.io/aatiwarishubaks2f1f3:${{ github.sha }}
        imagepullsecrets: |
          aatiwarishubdockerauth